// hangman/react/src/HangmanWord.tsx
type HangmanWordProps = {
  guessedLetters: string[];
  wordToGuess: string;
  reveal: boolean;
};

export default function HangmanWord({
  guessedLetters,
  wordToGuess,
  reveal = false,
}: HangmanWordProps) {
  return (
    <div
      style={{
        display: "flex",
        gap: ".25em",
        fontSize: "6rem",
        fontWeight: "bold",
        fontFamily: "monospace",
        textTransform: "uppercase",
      }}
    >
      {wordToGuess.split("").map((letter, index) => (
        <span style={{ borderBottom: ".1em solid black" }} key={index}>
          <span
            style={{
              visibility:
                guessedLetters.includes(letter) || reveal
                  ? "visible"
                  : "hidden",
              color:
                reveal && !guessedLetters.includes(letter) ? "red" : "black",
            }}
          >
            {letter}
          </span>
        </span>
      ))}
    </div>
  );
}

// hangman/svelte/src/lib/components/HangmanWord.svelte
<script lang="ts">
	export let guessedLetters: string[];
	export let wordToGuess: string;
	export let reveal: boolean = false;
</script>

<div class="wrapper">
	{#each wordToGuess?.split('') as letter, idx (idx)}
		{@const guessed = guessedLetters?.includes(letter)}
		<span class="bottom-border">
			<span class:invisible={!(reveal || guessed)} class:not-guessed={reveal && !guessed}>
				{letter}
			</span>
		</span>
	{/each}
</div>

<style>
	.wrapper {
		display: flex;
		gap: 0.25em;
		font-size: 6rem;
		font-weight: bold;
		font-family: monospace;
		text-transform: uppercase;
		color: black;
	}
	.bottom-border {
		border-bottom: 0.1em solid black;
	}
	.invisible {
		visibility: hidden;
	}
	.not-guessed {
		color: red;
	}
</style>
